name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          bb: latest
      - run: ./green build
      - run: ./green create --dry-run
